# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: devopsself
variables:
 name: devopsself
stages:
  - stage: build
    displayName: build stage
    jobs:
      - job: build_job
        displayName: build job
        pool:
         name: devopsself
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'manual-aksdevopsacr-svc'
            repository: 'custom2aksnginxapp1'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.SourceVersion)'
        - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)        
        - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)  
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'kube-manifests'
            publishLocation: 'Container'

